language: python

python:
  - "3.6"

addon:
  - postgresql: "9.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before script:
  - psql -c "create database ahsummerdb;" -U postgres

script:
  - python manage.py test
  - coverage
  - coveralls

after success:
  - coveralls
