# Generated by Django 2.1.5 on 2019-02-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190211_1741'),
        ('profiles', '0002_profile_date_of_birth'),
    ]

    operations = [
    ]
