# Generated by Django 2.1.5 on 2019-02-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('recipients',
                 models.ManyToManyField(related_name='notifications',
                                        related_query_name='notification',
                                        to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('allow_in_app_notifications',
                 models.BooleanField(default=True)),
                ('allow_email_notifications',
                 models.BooleanField(default=True)),
                ('profile', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('was_read_in_app', models.BooleanField(default=False)),
                ('email_was_sent', models.BooleanField(default=False)),
                ('notification',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to='notifications.Notification')),
                ('recipient',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='profiles.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notificationstatus',
            unique_together={('recipient', 'notification')},
        ),
    ]
