# Generated by Django 2.1.5 on 2019-02-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='favorited',
        ),
        migrations.AddField(
            model_name='article',
            name='favorited_by',
            field=models.ManyToManyField(
                blank=True, related_name='favorited_by',
                to='profiles.Profile'),
        ),
    ]
