# Generated by Django 2.1.5 on 2019-02-09 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rating'),
        ('articles', '0002_auto_20190207_1417'),
    ]

    operations = [
    ]
