# Generated by Django 2.1.5 on 2019-02-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190207_1417'),
        ('articles', '0002_auto_20190208_0656'),
    ]

    operations = [
    ]
