# Generated by Django 2.1.5 on 2019-02-11 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rating'),
        ('articles', '0003_merge_20190209_0739'),
    ]

    operations = [
    ]
