# Generated by Django 2.1.5 on 2019-02-11 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_merge_20190209_0751'),
        ('articles', '0004_merge_20190211_0645'),
    ]

    operations = [
    ]
