# Generated by Django 2.1.5 on 2019-02-11 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20190211_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
