# Generated by Django 2.1.5 on 2019-02-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_merge_20190214_1334'),
        ('articles', '0006_article_tag_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='articles.Article')),
                ('reporter', models.ForeignKey(
                    blank=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    to='profiles.Profile')),
            ],
        ),
    ]
