# Generated by Django 2.1.5 on 2019-02-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_bookmark'),
        ('articles', '0007_readstats'),
    ]

    operations = [
    ]
