# Generated by Django 2.1.5 on 2019-02-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_merge_20190221_1444'),
        ('articles', '0008_merge_20190221_1446'),
    ]

    operations = [
    ]
