# Generated by Django 2.1.5 on 2019-02-13 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_tag_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
        ('comments', '0002_auto_20190211_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('id', models.IntegerField(auto_created=True,
                                           blank=True,
                                           db_index=True, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True,
                                                    editable=False)),
                ('updated_at', models.DateTimeField(
                    blank=True,
                    editable=False,
                    null=True)),
                ('history_id', models.AutoField(primary_key=True,
                                                serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100,
                    null=True)),
                ('history_type', models.CharField(choices=[
                 ('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')],
                    max_length=1)),
                ('article', models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+',
                    to='articles.Article')),
                ('author', models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='profiles.Profile')),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCommentReply',
            fields=[
                ('id', models.IntegerField(
                    auto_created=True,
                    blank=True,
                    db_index=True, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(
                    blank=True,
                    editable=False)),
                ('updated_at', models.DateTimeField(
                    blank=True,
                    editable=False,
                    null=True)),
                ('history_id', models.AutoField(
                    primary_key=True,
                    serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(
                    max_length=100,
                    null=True)),
                ('history_type', models.CharField(
                    choices=[
                        ('+', 'Created'),
                        ('~', 'Changed'),
                        ('-', 'Deleted')],
                    max_length=1)),
                ('author', models.ForeignKey(
                    blank=True, db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+', to='profiles.Profile')),
                ('comment', models.ForeignKey(
                    blank=True,
                    db_constraint=False,
                    null=True,
                    on_delete=django.db.models.deletion.DO_NOTHING,
                    related_name='+',
                    to='comments.Comment')),
                ('history_user', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='+',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical comment reply',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
