# Generated by Django 2.1.5 on 2019-02-19 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0002_auto_20190211_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='disliked_by',
            field=models.ManyToManyField(
                related_name='disliked_comments',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='liked_by',
            field=models.ManyToManyField(
                related_name='liked_comments',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
