# Generated by Django 2.1.5 on 2019-02-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20190211_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenting_on',
            field=models.TextField(default=None, null=True),
        ),
    ]
