# Generated by Django 2.1.5 on 2019-02-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_historicalcomment_historicalcommentreply'),
        ('comments', '0003_auto_20190220_0230'),
    ]

    operations = [
    ]
