# Generated by Django 2.1.5 on 2019-02-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_historicalcomment_historicalcommentreply'),
        ('comments', '0003_comment_commenting_on'),
    ]

    operations = [
    ]
