# Generated by Django 2.1.5 on 2019-02-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_merge_20190221_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcomment',
            name='commenting_on',
            field=models.TextField(default=None, null=True),
        ),
    ]
