# Generated by Django 2.1.5 on 2019-02-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_historicalcomment_commenting_on'),
        ('comments', '0004_merge_20190221_1355'),
    ]

    operations = [
    ]
